// Shared keyword presets for job applications and user keyword management

export const TECHNICAL_SKILLS = [
  "react",
  "javascript",
  "typescript",
  "node.js",
  "python",
  "java",
  "c#",
  "php",
  "html",
  "css",
  "sql",
  "mongodb",
  "postgresql",
  "mysql",
  "aws",
  "azure",
  "docker",
  "kubernetes",
  "git",
  "rest api",
  "graphql",
  "microservices",
  "ci/cd",
  "testing",
  "jest",
  "cypress",
  "selenium",
  "linux",
  "windows",
  "macos",
  "angular",
  "vue.js",
  "express.js",
  "spring",
  "django",
  "flask",
  "laravel",
  "ruby on rails",
  "golang",
  "rust",
  "swift",
  "kotlin",
  "flutter",
  "react native",
  "terraform",
  "jenkins",
];

export const SOFT_SKILLS = [
  "communication",
  "teamwork",
  "leadership",
  "problem solving",
  "analytical thinking",
  "project management",
  "remote work",
  "collaboration",
  "mentoring",
  "training",
  "agile",
  "scrum",
  "adaptability",
  "creativity",
  "time management",
  "critical thinking",
  "decision making",
  "conflict resolution",
  "presentation skills",
  "customer service",
  "strategic planning",
  "multitasking",
  "attention to detail",
  "organizational skills",
];
